# Default values for container-blueprint.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullnameOverride: invitation-service
image:
  repository: test
  tag: stable
  pullPolicy: Always
  
ingress:
  serviceHost: test.com
  clusterIssuer: place
imagePullSecret: someSecret

deployment:
  containerPort: 443