apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  # different name
  name: certificate${CLUSTER_ISSUER}
  namespace: partsmasterdata
spec:
  # dedicate secret for the TLS cert
  secretName: certificate${CLUSTER_ISSUER}-secret
  issuerRef:
    # referencing the production issuer
    name: letsencrypt${CLUSTER_ISSUER}
    kind: ClusterIssuer
  dnsNames:
  - ${CATENA_SERVICE_URL}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: partsmasterdata-ingress
  namespace: partsmasterdata
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt$CLUSTER_ISSUER
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  tls:
  - hosts:
    - $CATENA_SERVICE_URL
    secretName: certificate${CLUSTER_ISSUER}-secret
  rules:
  - host: $CATENA_SERVICE_URL
    http:
      paths:
      - path: /partsmasterdata(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: partsmasterdata
            port:
              number: 8080

